import { Amenity, AvailabilityBlock, Photo, SiteSettings } from "@/lib/types";

const now = new Date().toISOString();

export const defaultSiteSettings: SiteSettings = {
  id: "default",
  villa_name: "L'oasis Villa",
  slogan: "Villa djerbienne privee - esprit chic et authentique",
  whatsapp_number: "0033641991176",
  messenger_name: "L'oasis Villa",
  hero_title: "Villa djerbienne privee a 5 min de la plage d'Aghir",
  hero_subtitle:
    "Piscine privee, jardin arbore, espace enfant et confort moderne au coeur de Djerba.",
  presentation_text:
    "Villa djerbienne privee sans vis-a-vis avec piscine, jardin, salon traditionnel et chambres climatisees.",
  experience_text:
    "Un sejour pense pour les familles et les groupes d'amis avec calme, intimite et prestations completes.",
  location_text:
    "Aghir, Djerba. A 5 min de la plage, 15 min de Midoun et Houmt Souk.",
  contact_text:
    "Reservation ouverte toute l'annee. Contactez-nous sur WhatsApp ou Messenger pour une reponse rapide.",
  meta_title: "L'oasis Villa - Location villa privee avec piscine a Djerba",
  meta_description:
    "Villa djerbienne sans vis-a-vis a Aghir, Djerba. Piscine privee, jardin, espace enfant, salle de sport, a 5 min de la plage.",
  og_title: "L'oasis Villa - Sejour premium a Djerba",
  og_description:
    "Villa privee premium a Djerba avec piscine, jardin, espace enfant et reservation toute l'annee.",
  og_image_url: "/images/villa/villa-15.jpeg",
  keywords:
    "villa djerba, location villa aghir, villa piscine djerba, villa familiale djerba",
  show_calendar: false,
  updated_at: now,
};

export const defaultAmenities: Amenity[] = [
  {
    id: "amenity-1",
    name: "Piscine privee",
    description: "Piscine exterieure reservee a la villa",
    icon: "waves",
    is_active: true,
    sort_order: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-2",
    name: "Jardin arbore",
    description: "Espace vert naturel et ombrage",
    icon: "trees",
    is_active: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-3",
    name: "Sans vis-a-vis",
    description: "Intimite totale pour votre sejour",
    icon: "shield",
    is_active: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-4",
    name: "Espace enfant",
    description: "Zone securisee pour enfants",
    icon: "toy-brick",
    is_active: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-5",
    name: "Salle de sport",
    description: "Equipements fitness de base",
    icon: "dumbbell",
    is_active: true,
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-6",
    name: "Cuisine equipee",
    description: "Cuisine complete pour cuisiner librement",
    icon: "chef-hat",
    is_active: true,
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-7",
    name: "Climatisation",
    description: "Climatisation dans les chambres",
    icon: "snowflake",
    is_active: true,
    sort_order: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-8",
    name: "Salon traditionnel",
    description: "Ambiance djerbienne authentique",
    icon: "sofa",
    is_active: true,
    sort_order: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-9",
    name: "Parking",
    description: "Stationnement sur place",
    icon: "car",
    is_active: true,
    sort_order: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-10",
    name: "A 5 min de la plage",
    description: "Acces rapide a la plage d'Aghir",
    icon: "map-pin",
    is_active: true,
    sort_order: 9,
    created_at: now,
    updated_at: now,
  },
];

export const defaultPhotos: Photo[] = [
  {
    id: "photo-1",
    title: "Piscine signature",
    category: "Piscine",
    image_url: "/images/villa/villa-15.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: true,
    sort_order: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-2",
    title: "Facade principale",
    category: "Exterieur",
    image_url: "/images/villa/villa-04.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-3",
    title: "Piscine privee vue aerienne",
    category: "Piscine",
    image_url: "/images/villa/villa-15.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-4",
    title: "Cuisine equipee",
    category: "Cuisine",
    image_url: "/images/villa/villa-14.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-5",
    title: "Jardin et oliviers",
    category: "Jardin",
    image_url: "/images/villa/villa-12.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-6",
    title: "Espace enfant",
    category: "Espace enfant",
    image_url: "/images/villa/villa-08.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-7",
    title: "Vue exterieure 1",
    category: "Exterieur",
    image_url: "/images/villa/villa-01.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-8",
    title: "Vue exterieure 2",
    category: "Exterieur",
    image_url: "/images/villa/villa-02.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-9",
    title: "Salon traditionnel 1",
    category: "Salon",
    image_url: "/images/villa/villa-03.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-10",
    title: "Chambre 1",
    category: "Chambres",
    image_url: "/images/villa/villa-05.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 9,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-11",
    title: "Chambre 2",
    category: "Chambres",
    image_url: "/images/villa/villa-06.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 10,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-12",
    title: "Salon traditionnel 2",
    category: "Salon",
    image_url: "/images/villa/villa-07.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 11,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-13",
    title: "Piscine 2",
    category: "Piscine",
    image_url: "/images/villa/villa-09.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 12,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-14",
    title: "Piscine 3",
    category: "Piscine",
    image_url: "/images/villa/villa-10.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 13,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-15",
    title: "Cuisine 2",
    category: "Cuisine",
    image_url: "/images/villa/villa-11.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 14,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-16",
    title: "Jardin 2",
    category: "Jardin",
    image_url: "/images/villa/villa-13.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 15,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-17",
    title: "Chambre 3",
    category: "Chambres",
    image_url: "/images/villa/villa-16.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 16,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-18",
    title: "Salon 3",
    category: "Salon",
    image_url: "/images/villa/villa-17.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 17,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-19",
    title: "Vue exterieure 3",
    category: "Exterieur",
    image_url: "/images/villa/villa-18.jpeg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 18,
    created_at: now,
    updated_at: now,
  },
];

export const defaultAvailability: AvailabilityBlock[] = [
  {
    id: "availability-1",
    start_date: "2026-07-01",
    end_date: "2026-07-10",
    status: "Reserve",
    note: "Reservation famille",
    created_at: now,
    updated_at: now,
  },
  {
    id: "availability-2",
    start_date: "2026-08-15",
    end_date: "2026-08-18",
    status: "Maintenance",
    note: "Entretien piscine",
    created_at: now,
    updated_at: now,
  },
];
