import { Amenity, AvailabilityBlock, Photo, SiteSettings } from "@/lib/types";

const now = new Date().toISOString();

export const defaultSiteSettings: SiteSettings = {
  id: "default",
  villa_name: "Villa Dar Aghir",
  slogan: "L'Oasis Djerbienne",
  whatsapp_number: "0033641991176",
  messenger_name: "L'oasis Villa",
  hero_title: "Villa djerbienne privee a 5 min de la plage d'Aghir",
  hero_subtitle:
    "Piscine privee, jardin arbore, espace enfant et confort moderne au coeur de Djerba.",
  presentation_text:
    "Villa djerbienne privee sans vis-a-vis avec piscine, jardin, salon traditionnel et chambres climatisees.",
  experience_text:
    "Un sejour pense pour les familles et les groupes d'amis avec calme, intimite et prestations completes.",
  location_text:
    "Aghir, Djerba. A 5 min de la plage, 15 min de Midoun et Houmt Souk.",
  contact_text:
    "Reservation ouverte toute l'annee. Contactez-nous sur WhatsApp ou Messenger pour une reponse rapide.",
  meta_title: "Villa Dar Aghir - Location villa privee avec piscine a Djerba",
  meta_description:
    "Villa djerbienne sans vis-a-vis a Aghir, Djerba. Piscine privee, jardin, espace enfant, salle de sport, a 5 min de la plage.",
  og_title: "Villa Dar Aghir - L'Oasis Djerbienne",
  og_description:
    "Villa privee premium a Djerba avec piscine, jardin, espace enfant et reservation toute l'annee.",
  og_image_url: "/images/villa/hero.svg",
  keywords:
    "villa djerba, location villa aghir, villa piscine djerba, villa familiale djerba",
  show_calendar: false,
  updated_at: now,
};

export const defaultAmenities: Amenity[] = [
  {
    id: "amenity-1",
    name: "Piscine privee",
    description: "Piscine exterieure reservee a la villa",
    icon: "waves",
    is_active: true,
    sort_order: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-2",
    name: "Jardin arbore",
    description: "Espace vert naturel et ombrage",
    icon: "trees",
    is_active: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-3",
    name: "Sans vis-a-vis",
    description: "Intimite totale pour votre sejour",
    icon: "shield",
    is_active: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-4",
    name: "Espace enfant",
    description: "Zone securisee pour enfants",
    icon: "toy-brick",
    is_active: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-5",
    name: "Salle de sport",
    description: "Equipements fitness de base",
    icon: "dumbbell",
    is_active: true,
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-6",
    name: "Cuisine equipee",
    description: "Cuisine complete pour cuisiner librement",
    icon: "chef-hat",
    is_active: true,
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-7",
    name: "Climatisation",
    description: "Climatisation dans les chambres",
    icon: "snowflake",
    is_active: true,
    sort_order: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-8",
    name: "Salon traditionnel",
    description: "Ambiance djerbienne authentique",
    icon: "sofa",
    is_active: true,
    sort_order: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-9",
    name: "Parking",
    description: "Stationnement sur place",
    icon: "car",
    is_active: true,
    sort_order: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "amenity-10",
    name: "A 5 min de la plage",
    description: "Acces rapide a la plage d'Aghir",
    icon: "map-pin",
    is_active: true,
    sort_order: 9,
    created_at: now,
    updated_at: now,
  },
];

export const defaultPhotos: Photo[] = [
  {
    id: "photo-1",
    title: "Hero villa",
    category: "Exterieur",
    image_url: "/images/villa/hero.svg",
    storage_path: null,
    is_published: true,
    is_hero: true,
    sort_order: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-2",
    title: "Piscine privee",
    category: "Piscine",
    image_url: "/images/villa/piscine.svg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-3",
    title: "Suite climatisee",
    category: "Chambres",
    image_url: "/images/villa/chambre.svg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-4",
    title: "Salon djerbien",
    category: "Salon",
    image_url: "/images/villa/salon.svg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-5",
    title: "Jardin",
    category: "Jardin",
    image_url: "/images/villa/jardin.svg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "photo-6",
    title: "Cuisine",
    category: "Cuisine",
    image_url: "/images/villa/cuisine.svg",
    storage_path: null,
    is_published: true,
    is_hero: false,
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
];

export const defaultAvailability: AvailabilityBlock[] = [
  {
    id: "availability-1",
    start_date: "2026-07-01",
    end_date: "2026-07-10",
    status: "Reserve",
    note: "Reservation famille",
    created_at: now,
    updated_at: now,
  },
  {
    id: "availability-2",
    start_date: "2026-08-15",
    end_date: "2026-08-18",
    status: "Maintenance",
    note: "Entretien piscine",
    created_at: now,
    updated_at: now,
  },
];
